#!/usr/bin/env python
"""Export paper-ready tables (CSV + LaTeX) from a comparative benchmark run.

Outputs to ``results/tables/``:

* ``ranking_full.csv/.tex``    — every condition: ranks, STOI, SNR, per-ASR
  ΔWER, cross-family ΔWER, illustrative HSR, Pareto flag.
* ``top10_attack.csv/.tex``    — ten strongest attacks (cross-family ΔWER).
* ``top10_human.csv/.tex``     — ten most human-transparent transforms.
* ``lambda_sweep.csv/.tex``    — base-paper λ-grid mirror incl. "None"
  control column.
* ``family_summary.csv/.tex``  — per-family means.

Every table carries a caption noting the dataset protocol and that HSR is
illustrative (STOI-derived, no human study).
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

import pandas as pd

HSR_NOTE = (
    "HSR is illustrative (STOI-derived proxy; no human study conducted). "
    "Dataset: base-paper subset protocol of Schonherr et al. 2018 "
    "(arXiv:1808.05665); see run's dataset\\_manifest.json."
)

LATEX_COLS = {
    "condition_id": ("Condition", "l"),
    "transform_key": ("Transform", "l"),
    "margin_db": ("$\\lambda$ (dB)", "c"),
    "family": ("Fam", "c"),
    "kind": ("Kind", "c"),
    "n": ("n", "r"),
    "stoi_mean": ("STOI$\\uparrow$", "r"),
    "mean_stoi": ("mean STOI", "r"),
    "snr_mean": ("SNR (dB)", "r"),
    "wer_whisper_tiny_delta": ("$\\Delta$WER Whisper", "r"),
    "wer_vosk_small_en_delta": ("$\\Delta$WER Vosk", "r"),
    "cross_delta_wer": ("cross-$\\Delta$WER $\\uparrow$", "r"),
    "mean_cross_delta_wer": ("mean cross-$\\Delta$WER", "r"),
    "std_cross_delta_wer": ("SD cross-$\\Delta$WER", "r"),
    "hsr": ("HSR (ill.)", "r"),
    "mean_hsr": ("mean HSR (ill.)", "r"),
    "hag": ("HAG", "r"),
    "human_rank": ("H-rank", "r"),
    "attack_rank": ("A-rank", "r"),
    "gap_rank": ("GAP-rank", "r"),
    "quality_rank": ("Q-rank", "r"),
    "pareto": ("Pareto", "c"),
    "best_condition": ("Best condition", "l"),
}


def _latex_escape(s: str) -> str:
    for a, b in (("_", r"\_"), ("%", r"\%"), ("&", r"\&"), ("#", r"\#")):
        s = s.replace(a, b)
    return s


def _fmt_val(col: str, v) -> str:
    if pd.isna(v):
        return "—"
    if col == "pareto":
        return "★" if bool(v) else ""
    if col in ("human_rank", "attack_rank", "gap_rank", "quality_rank", "n"):
        return str(int(v))
    if col == "margin_db":
        return str(v) if isinstance(v, str) else f"{float(v):g}"
    if col in ("condition_id", "family", "kind", "transform_key",
               "best_condition"):
        return _latex_escape(str(v))
    return f"{float(v):.3f}"


def write_latex(df: pd.DataFrame, path: Path, caption: str,
                label: str, cols: list[str] | None = None) -> None:
    cols = cols or [c for c in LATEX_COLS if c in df.columns]
    spec = LATEX_COLS
    header = " & ".join(spec[c][0] for c in cols) + " \\\\"
    aligns = "".join(spec[c][1] for c in cols)
    lines = [
        "% Auto-generated by scripts/make_tables.py",
        r"\begin{table*}[t]",
        r"\centering",
        f"\\caption{{{caption}}}",
        f"\\label{{{label}}}",
        r"\small",
        f"\\begin{{tabular}}{{{aligns}}}",
        r"\toprule",
        header,
        r"\midrule",
    ]
    for _, row in df.iterrows():
        lines.append(" & ".join(_fmt_val(c, row[c]) for c in cols) + r" \\")
    lines += [r"\bottomrule", r"\end{tabular}", r"\end{table*}"]
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(description=__doc__.split("\n", 1)[0])
    p.add_argument("--run", type=Path,
                   default=Path("results/comparative/main"))
    p.add_argument("--out", type=Path, default=Path("results/tables"))
    args = p.parse_args(argv)

    summary_path = args.run / "summary.csv"
    if not summary_path.exists():
        print(f"missing {summary_path} — run the benchmark first")
        return 1
    df = pd.read_csv(summary_path)
    df["pareto"] = df["pareto"].fillna(False)
    args.out.mkdir(parents=True, exist_ok=True)

    written: list[Path] = []

    def _emit(frame: pd.DataFrame, name: str, caption: str, label: str,
              cols: list[str] | None = None) -> None:
        csvp = args.out / f"{name}.csv"
        frame.to_csv(csvp, index=False)
        written.append(csvp)
        texp = args.out / f"{name}.tex"
        write_latex(frame, texp, caption, label, cols=cols)
        written.append(texp)

    # 1. full ranking
    full = df.sort_values("attack_rank", na_position="last")
    _emit(
        full, "ranking_full",
        "Complete ranking of all evaluated conditions by cross-family "
        f"attack strength. {HSR_NOTE}", "tab:ranking_full",
    )

    # 2/3. top-10 views
    ranked = df[df.kind != "original"]
    if ranked["attack_rank"].notna().any():
        top_a = ranked.nsmallest(10, "attack_rank")
        _emit(top_a, "top10_attack",
              "Ten strongest attacks (mean cross-family $\\Delta$WER over "
              f"Whisper tiny and Vosk). {HSR_NOTE}", "tab:top10_attack",
              cols=[c for c in (
                  "attack_rank", "condition_id", "family",
                  "wer_whisper_tiny_delta", "wer_vosk_small_en_delta",
                  "cross_delta_wer", "stoi_mean", "hsr", "pareto",
              ) if c in df.columns])
    top_h = ranked.nsmallest(10, "human_rank")
    _emit(top_h, "top10_human",
          "Ten most human-transparent transforms (mean STOI proxy, higher "
          f"is more transparent). {HSR_NOTE}", "tab:top10_human",
          cols=[c for c in (
              "human_rank", "condition_id", "family", "stoi_mean",
              "snr_mean", "cross_delta_wer", "hsr",
          ) if c in df.columns])

    # 4. lambda sweep grid
    sweep = df[df.kind == "sweep"].copy()
    if not sweep.empty:
        rows = []
        control = df[df.condition_id.str.startswith("control.", na=False)]
        for key, g in sweep.groupby("transform_key"):
            g = g.sort_values("margin_db")
            for _, r in g.iterrows():
                rows.append({
                    "transform_key": key, "margin_db": r.margin_db,
                    "stoi_mean": r.stoi_mean,
                    "wer_whisper_tiny_delta": r.get(
                        "wer_whisper_tiny_delta"),
                    "wer_vosk_small_en_delta": r.get(
                        "wer_vosk_small_en_delta"),
                    "cross_delta_wer": r.cross_delta_wer,
                    "snr_mean": r.snr_mean,
                })
            if not control.empty:
                c = control.iloc[0]
                rows.append({
                    "transform_key": key, "margin_db": "None",
                    "stoi_mean": c.stoi_mean,
                    "wer_whisper_tiny_delta": c.get(
                        "wer_whisper_tiny_delta"),
                    "wer_vosk_small_en_delta": c.get(
                        "wer_vosk_small_en_delta"),
                    "cross_delta_wer": c.cross_delta_wer,
                    "snr_mean": c.snr_mean,
                })
        sw = pd.DataFrame(rows)
        tex_cols = ["transform_key", "margin_db", "stoi_mean",
                    "wer_whisper_tiny_delta", "wer_vosk_small_en_delta",
                    "cross_delta_wer", "snr_mean"]
        cap = ("Hearing-threshold margin sweep ($\\lambda$ grid of the base "
               "paper) including the unconstrained ``None'' control "
               f"(power-matched to $\\lambda$=0). {HSR_NOTE}")
        _emit(sw, "lambda_sweep", cap, "tab:lambda_sweep", cols=tex_cols)

    # 5. family summary
    import numpy as np

    fam_rows = []
    for f, g in df[df.kind != "original"].groupby("family"):
        a = g.cross_delta_wer.dropna()
        fam_rows.append({
            "family": f, "n": len(g),
            "mean_stoi": g.stoi_mean.mean(),
            "mean_cross_delta_wer": a.mean() if len(a) else np.nan,
            "std_cross_delta_wer": a.std(ddof=1) if len(a) > 1 else np.nan,
            "mean_hsr": g.get("hsr", pd.Series(dtype=float)).mean(),
            "best_condition": (
                g.loc[g.cross_delta_wer.idxmax(), "condition_id"]
                if a.any() else ""
            ),
        })
    fam = pd.DataFrame(fam_rows).sort_values("mean_cross_delta_wer",
                                             na_position="last")
    _emit(fam, "family_summary",
          "Family-level summary of attack strength and human "
          f"intelligibility. {HSR_NOTE}", "tab:family_summary",
          cols=["family", "n", "mean_stoi", "mean_cross_delta_wer",
                "std_cross_delta_wer", "mean_hsr", "best_condition"])

    for w in written:
        print(f"wrote {w}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
